### ISSUE TITLE
We should not hardcode CORS origins and even use the same origins in every routes

### ISSUE THREAD

**Issue by GToidZ** [SPaM-Skill-Issue/sota-backend#1]
We'll be making a route to generate an API token for our partnered teams, which in reality, we should not ever expose the route to be accessible. By using CORS, and setting the origin to our server only, we can prevent access even if our source code exposes how we generate API tokens.

https://github.com/SPaM-Skill-Issue/sota-backend/blob/9db93ba3274cf1324031e4c888c7ee812c0ea12b/main.py#L5-L13

## To do list
- [x] Externalize CORS origins configuration using `python-decouple`
- [x] Use the CORS origins config for all routes, except token generation.
- [x] Use internal only CORS config (localhost, maybe) for token generation route.

## Ideas & Suggestions
Use sub-applications, per https://fastapi.tiangolo.com/advanced/sub-applications/, we can use different sets of configuration that way.

**Comment by Halcyon905** [comment]
I have made changes according to the TODO list.

**Comment by GToidZ** [comment]
Okay, looking good in your work. Closing this issue.
