### ISSUE TITLE
List is not using capital letter in medals_router.py line 59

### ISSUE THREAD

**Issue by MarojT** [SPaM-Skill-Issue/sota-backend#16]
![skillissue](https://github.com/SPaM-Skill-Issue/sota-backend/assets/59698469/4338da78-321d-4663-8e03-07226718d84f)

the program goes boom

**Comment by GToidZ** [comment]
This is because of Python 3.8 does not yet implement [PEP 585](https://peps.python.org/pep-0585/). The PEP however was implemented in 3.9 which is one major version up. Seems like `typing.List` for example, is going to be deprecated too.
